#pragma once
// Independent, untimed multi-GPU check of the explicitly formed full Q.
// Q is generated by the returned handle in its selected arithmetic. The Gram
// products use IEEE storage precision, with TF32 disabled, and reduce complete
// row partitions. Every entry of Q^T Q-I is inspected, including trailing Q
// columns for a tall factorization. This does not replace the residual check.
namespace tqr {
inline int multi_q_formation_width(int m){
 int width=512;
#ifdef TQR_MULTI_FIXED_DRIVER
 if(const char*value=std::getenv("TQR_MULTI_Q_FORM_WIDTH")){
  std::string text(value);size_t used=0;width=std::stoi(text,&used);
  if(used!=text.size()||width<512||width>8192||width%512)
   throw std::runtime_error("multi_q_formation_width_multiple_of_512_up_to_8192");
 }
#endif
 return std::min(m,width);
}
template<class T> __global__ void multi_identity_columns(T*x,int ld,int nr,int begin,int q,int first){
 for(size_t e=size_t(blockIdx.x)*blockDim.x+threadIdx.x;e<size_t(nr)*q;e+=size_t(blockDim.x)*gridDim.x){
  const int row=int(e%nr),col=int(e/nr);x[row+size_t(col)*ld]=begin+row==first+col?T(1):T(0);
 }
}
template<class T> __global__ void multi_gram_error(const T*g,int m,int q,int first,double*out){
 double sum=0,diag=0,off=0;
 for(size_t e=size_t(blockIdx.x)*blockDim.x+threadIdx.x;e<size_t(m)*q;e+=size_t(blockDim.x)*gridDim.x){
  const bool diagonal=int(e%m)==first+int(e/m);
  double error=double(g[e])-(diagonal?1.0:0.0);
  if(!isfinite(error))error=INFINITY;
  sum+=error*error;if(diagonal)diag=fmax(diag,fabs(error));else off=fmax(off,fabs(error));
 }
 __shared__ double sums[256],diags[256],offs[256];
 const int t=threadIdx.x;sums[t]=sum;diags[t]=diag;offs[t]=off;__syncthreads();
 for(int stride=128;stride;stride/=2){if(t<stride){sums[t]+=sums[t+stride];diags[t]=fmax(diags[t],diags[t+stride]);offs[t]=fmax(offs[t],offs[t+stride]);}__syncthreads();}
 if(t==0){out[3*blockIdx.x]=sums[0];out[3*blockIdx.x+1]=diags[0];out[3*blockIdx.x+2]=offs[0];}
}

class MultiGramComm {
public:
 ncclComm_t comm=nullptr;
 explicit MultiGramComm(Context&ctx){
  ncclUniqueId id;if(ctx.rank==0)NC(ncclGetUniqueId(&id));
  if(MPI_Bcast(&id,int(sizeof(id)),MPI_BYTE,0,MPI_COMM_WORLD)!=MPI_SUCCESS)
   throw std::runtime_error("multi_gram_unique_id");
  NC(ncclCommInitRank(&comm,ctx.size,id,ctx.rank));
 }
 ~MultiGramComm(){if(comm)ncclCommDestroy(comm);}
};

template<class T,class E> json validate_multi_full_gram(E&engine,TiledMatrix<T>&a,Context&ctx,const TiledPlan&plan){
 if(ctx.size<2)throw std::runtime_error("full_gram_validation_requires_multi_gpu");
 const double started=seconds();const int width=std::min(a.m,512),form_width=multi_q_formation_width(a.m),ld=descriptor_ld(a.nr,0);
 const size_t qwords=checked_mul(size_t(ld),size_t(a.m));
 const size_t gwords=checked_mul(size_t(a.m),size_t(width));
 const char*reuse_env=std::getenv("TQR_MULTI_GRAM_REUSE_OUTPUT");
 const bool reuse=reuse_env&&std::string(reuse_env)=="1";
 if(reuse&&!engine.validation_can_borrow_output(a))throw std::runtime_error("full_gram_output_reuse_requires_independent_cyclic_factors_and_m_le_n");
 // apply_q allocates a temporary cyclic operand only for the current column
 // block. The complete Q never needs a second full cyclic copy.
 const size_t blockwords=checked_mul(size_t(a.nr+plan.b+1),size_t(form_width));
 const size_t required=checked_add(checked_mul(checked_add(checked_add(reuse?0:qwords,gwords),2*blockwords),sizeof(T)),64ULL<<20);
 size_t free_bytes=0,total=0;CU(cudaMemGetInfo(&free_bytes,&total));
 const auto admission=ctx.all_records({{"rank",ctx.rank},{"required_extra_bytes",required},{"free_bytes",free_bytes},
  {"Q_formation_block_columns",form_width},{"gram_block_columns",width}});
 for(const auto&r:admission)if(r.at("required_extra_bytes").template get<size_t>()>r.at("free_bytes").template get<size_t>())
  throw std::runtime_error("full_gram_extra_capacity_before_allocation");
 TiledMatrix<T> fullq(a.m,reuse?0:a.m,ctx.size,ctx.rank),columns(a.m,form_width,ctx.size,ctx.rank);
 if(reuse){fullq.n=a.m;fullq.a=Buffer<T>(a.a.p,qwords);}
 Buffer<T>gram(gwords);Buffer<double>summary(3*256);Stream st;MultiGramComm collective(ctx);
 int status=0;size_t columns_checked=0,entries_checked=0;
 // Only untimed Q formation batches change. Gram GEMMs, every-entry
 // inspection, norm-reduction groups and tolerances retain their 512-column
 // layout. Retained QR factors and the timed factorization are untouched.
 for(int first=0;first<a.m;first+=form_width){
  const int q=std::min(form_width,a.m-first);columns.n=q;
  multi_identity_columns<T><<<256,256,0,st>>>(columns.a.p,columns.ld,columns.nr,columns.begin,q,first);CU(cudaGetLastError());st.sync();
  status=std::max(status,engine.apply_q(columns,false));
  if(columns.nr)CU(cudaMemcpy2DAsync(fullq.a.p+size_t(first)*fullq.ld,size_t(fullq.ld)*sizeof(T),columns.a.p,size_t(columns.ld)*sizeof(T),size_t(columns.nr)*sizeof(T),q,cudaMemcpyDeviceToDevice,st));
  st.sync();columns_checked+=q;
 }
 cublasHandle_t handle=nullptr;blas_check(cublasCreate(&handle));
 blas_check(cublasSetStream(handle,st));blas_check(cublasSetMathMode(handle,CUBLAS_PEDANTIC_MATH));
 const T one=T(1),zero=T(0);long double energy=0;double diag=0,off=0;
 for(int first=0;first<a.m;first+=width){
  const int q=std::min(width,a.m-first);
  if(fullq.nr){
   if constexpr(std::is_same_v<T,double>)blas_check(cublasDgemm(handle,CUBLAS_OP_T,CUBLAS_OP_N,a.m,q,fullq.nr,&one,fullq.a.p,fullq.ld,fullq.a.p+size_t(first)*fullq.ld,fullq.ld,&zero,gram.p,a.m));
   else blas_check(cublasSgemm(handle,CUBLAS_OP_T,CUBLAS_OP_N,a.m,q,fullq.nr,&one,fullq.a.p,fullq.ld,fullq.a.p+size_t(first)*fullq.ld,fullq.ld,&zero,gram.p,a.m));
  }else CU(cudaMemsetAsync(gram.p,0,size_t(a.m)*q*sizeof(T),st));
  NC(ncclAllReduce(gram.p,gram.p,size_t(a.m)*q,sizeof(T)==8?ncclDouble:ncclFloat,ncclSum,collective.comm,st));
  multi_gram_error<T><<<256,256,0,st>>>(gram.p,a.m,q,first,summary.p);CU(cudaGetLastError());st.sync();
  const auto values=summary.download();
  for(int j=0;j<256;++j){energy+=values[3*j];diag=std::max(diag,values[3*j+1]);off=std::max(off,values[3*j+2]);}
  entries_checked+=size_t(a.m)*q;
 }
 blas_check(cublasDestroy(handle));
 if(reuse)engine.validation_restore_output(a);
 const double fro=std::sqrt(double(energy)),relative=fro/std::sqrt(double(a.m));
 const double u=working_unit_roundoff<T>();
 const double tol=std::min(0.01,32*u*(std::sqrt(double(a.m))+std::sqrt(double(a.n))+plan.b)*(1+std::ceil(std::log2(std::max(1,ceildiv(a.m,plan.leaf))))));
 const bool pass=status==0&&columns_checked==size_t(a.m)&&entries_checked==size_t(a.m)*a.m&&std::isfinite(fro)&&relative<=tol;
 const auto ranks=ctx.all_records({{"rank",ctx.rank},{"pass",pass},{"orthogonality_fro",fro},{"orthogonality_fro_relative_to_identity",relative},{"diagonal_error_inf",diag},{"off_diagonal_error_inf",off}});
 bool all_pass=true;for(const auto&r:ranks)all_pass=all_pass&&r.at("pass").template get<bool>();
 return {{"pass",all_pass},{"scope","all entries of explicit full Q^T Q-I; no sampling"},{"Q_storage",reuse?"borrowed redundant slab output after residual check; independent cyclic R/V and full-Q handle retained; slab factors restored before return":"separate full-Q allocation"},{"Q_arithmetic",precision_mode_name<T>()},{"gram_arithmetic",sizeof(T)==8?"IEEE FP64 DGEMM and FP64 rank reduction":"IEEE FP32 SGEMM (pedantic, TF32 disabled) and FP32 rank reduction"},{"norm_accumulation","FP64 block reductions and host long-double accumulation"},{"full_Q_columns_checked",columns_checked},{"gram_entries_checked_per_rank",entries_checked},{"orthogonality_fro",fro},{"orthogonality_fro_relative_to_identity",relative},{"diagonal_error_inf",diag},{"off_diagonal_error_inf",off},{"engineering_tolerance",tol},{"unit_roundoff",u},{"paper_acceptance","separate matched-precision assessment; engineering pass alone is insufficient"},{"admission",admission},{"rank_results",ranks},{"validation_s",seconds()-started}};
}
}
